### ISSUE TITLE
Public personal info of participants

### ISSUE THREAD

**Issue by simonbengtsson** [gbgstartuphack/teamsigns#1]
Hi! Just happened to see that all personal information of the participants are publicly available in `responses.tsv`. Is that intentional?

**Comment by odsod** [comment]
Nope, sorry about that, looks like I forgot to .gitignore the data file. This was all done in a rush.

I don't have access to this repo anymore, so someone in the org should remove it from the history. @hinken

**Comment by ohlsont** [comment]
I think i've fixed it. I should also be removed from all git history files

**Comment by simonbengtsson** [comment]
Cool! I didn't really care, but thought that I would let you know. You find a lot of interesting things when you google your email!
